/**
 * This is an autogenerated netlist code from CircuitVerse. Verilog Code can be
 * tested on https://www.edaplayground.com/ using Icarus Verilog 0.9.7. This is an
 * experimental module and some manual changes make need to be done in order for
 * this to work.
 *
 * If you have any ideas/suggestions or bug fixes, raise an issue
 * on https://github.com/CircuitVerse/CircuitVerse/issues/new/choose
 */

/*
  Element Usage Report
    Button - 5 times
    SRflipFlop - 21 times
    Output - 5 times
    XorGate - 8 times
    NotGate - 15 times
    TriState - 23 times
    AndGate - 8 times
    Clock - 1 times
    Input - 4 times
*/

/*
  Usage Instructions and Tips
    Labels - Ensure unique label names and avoid using verilog keywords
    Warnings - Connect all optional inputs to remove warnings
    Button - Buttons are not natively supported in verilog, consider using Inputs instead
    Clock - Use a single global clock
*/

// Sample Testbench Code - Uncomment to use

/*
module TestBench();

  reg inp_0, inp_1, inp_2, inp_3, clk_0;

  wire out_0, out_1, out_2, out_3, out_4;

  Main DUT0(out_0, out_1, out_2, out_3, out_4, clk_0, inp_0, inp_1, inp_2, inp_3);

  always begin
    #10
    clk_0 = 0;
    #10
    clk_0 = 1;
  end

  initial begin
    inp_0 = 0;
    inp_1 = 0;
    inp_2 = 0;
    inp_3 = 0;

    #15
    $display("out_0 = %b", out_0);
    $display("out_1 = %b", out_1);
    $display("out_2 = %b", out_2);
    $display("out_3 = %b", out_3);
    $display("out_4 = %b", out_4);

    #10
    $display("out_0 = %b", out_0);
    $display("out_1 = %b", out_1);
    $display("out_2 = %b", out_2);
    $display("out_3 = %b", out_3);
    $display("out_4 = %b", out_4);

    $finish;

  end
endmodule

*/

module Main(out_0, out_1, out_2, out_3, out_4, clk_0, inp_0, inp_1, inp_2, inp_3);
  output out_0,  out_1,  out_2,  out_3,  out_4;
  input inp_0, inp_1, inp_2, inp_3, clk_0;
  wire Button_4_out, SRflipFlop_20_Q, SRflipFlop_19_Q, SRflipFlop_18_Q, SRflipFlop_17_Q, Button_3_out, SRflipFlop_16_Q, xor_7_out, not_10_out, TriState_13_out, SRflipFlop_11_Q, TriState_20_out, not_12_out, and_5_out, TriState_16_out, TriState_15_out, SRflipFlop_12_Q, TriState_21_out, not_13_out, xor_5_out, TriState_17_out, TriState_18_out, SRflipFlop_14_Q, TriState_22_out, not_14_out, xor_6_out, not_8_out, SRflipFlop_15_Q, and_7_out, not_7_out, SRflipFlop_13_Q, and_6_out, SRflipFlop_10_Q, xor_4_out, TriState_14_out, not_6_out, TriState_12_out, SRflipFlop_9_Q, TriState_19_out, not_11_out, and_4_out, Button_2_out, SRflipFlop_6_Q, TriState_8_out, not_5_out, SRflipFlop_8_Q, xor_3_out, not_4_out, TriState_7_out, SRflipFlop_7_Q, Button_1_out, SRflipFlop_3_Q, xor_0_out, TriState_1_out, TriState_2_out, SRflipFlop_2_Q, xor_1_out, TriState_4_out, TriState_5_out, SRflipFlop_1_Q, and_2_out, xor_2_out, TriState_6_out, not_3_out, SRflipFlop_5_Q, not_2_out, SRflipFlop_4_Q, and_1_out, not_1_out, TriState_0_out, SRflipFlop_0_Q, and_0_out, Button_0_out, TriState_3_out, not_0_out, not_9_out;
  Button0 Button_4(Button_4_out);
  SRflipFlop SRflipFlop_20(SRflipFlop_20_Q, , TriState_22_out, not_14_out, Button_4_out, , );
  assign out_1 = SRflipFlop_20_Q;
  SRflipFlop SRflipFlop_19(SRflipFlop_19_Q, , TriState_21_out, not_13_out, Button_4_out, , );
  assign out_2 = SRflipFlop_19_Q;
  SRflipFlop SRflipFlop_18(SRflipFlop_18_Q, , TriState_20_out, not_12_out, Button_4_out, , );
  assign out_3 = SRflipFlop_18_Q;
  SRflipFlop SRflipFlop_17(SRflipFlop_17_Q, , TriState_19_out, not_11_out, Button_4_out, , );
  assign out_4 = SRflipFlop_17_Q;
  Button1 Button_3(Button_3_out);
  SRflipFlop SRflipFlop_16(SRflipFlop_16_Q, , SRflipFlop_11_Q, Button_3_out, , , );
  assign xor_7_out = SRflipFlop_16_Q ^ SRflipFlop_11_Q;
  assign not_10_out = ~xor_7_out;
  assign TriState_13_out = (not_10_out!=0) ? TriState_14_out : 1'b?;
  SRflipFlop SRflipFlop_11(SRflipFlop_11_Q, , TriState_13_out, and_5_out, , , );
  assign TriState_20_out = (SRflipFlop_11_Q!=0) ? SRflipFlop_8_Q : 1'b?;
  assign not_12_out = ~TriState_20_out;
  assign and_5_out = not_9_out & SRflipFlop_11_Q;
  assign TriState_16_out = (xor_7_out!=0) ? TriState_3_out : 1'b?;
  assign TriState_15_out = (not_7_out!=0) ? TriState_16_out : 1'b?;
  SRflipFlop SRflipFlop_12(SRflipFlop_12_Q, , TriState_15_out, and_6_out, , , );
  assign TriState_21_out = (SRflipFlop_12_Q!=0) ? SRflipFlop_8_Q : 1'b?;
  assign not_13_out = ~TriState_21_out;
  assign xor_5_out = SRflipFlop_13_Q ^ SRflipFlop_12_Q;
  assign TriState_17_out = (xor_5_out!=0) ? TriState_3_out : 1'b?;
  assign TriState_18_out = (not_8_out!=0) ? TriState_17_out : 1'b?;
  SRflipFlop SRflipFlop_14(SRflipFlop_14_Q, , TriState_18_out, and_7_out, , , );
  assign TriState_22_out = (SRflipFlop_14_Q!=0) ? SRflipFlop_8_Q : 1'b?;
  assign not_14_out = ~TriState_22_out;
  assign xor_6_out = SRflipFlop_15_Q ^ SRflipFlop_14_Q;
  assign not_8_out = ~xor_6_out;
  SRflipFlop SRflipFlop_15(SRflipFlop_15_Q, , SRflipFlop_14_Q, Button_3_out, , , );
  assign and_7_out = not_9_out & SRflipFlop_14_Q;
  assign not_7_out = ~xor_5_out;
  SRflipFlop SRflipFlop_13(SRflipFlop_13_Q, , SRflipFlop_12_Q, Button_3_out, , , );
  assign and_6_out = not_9_out & SRflipFlop_12_Q;
  SRflipFlop SRflipFlop_10(SRflipFlop_10_Q, , SRflipFlop_9_Q, Button_3_out, , , );
  assign xor_4_out = SRflipFlop_10_Q ^ SRflipFlop_9_Q;
  assign TriState_14_out = (xor_4_out!=0) ? TriState_3_out : 1'b?;
  assign not_6_out = ~xor_4_out;
  assign TriState_12_out = (not_6_out!=0) ? TriState_3_out : 1'b?;
  SRflipFlop SRflipFlop_9(SRflipFlop_9_Q, , TriState_12_out, and_4_out, , , );
  assign TriState_19_out = (SRflipFlop_9_Q!=0) ? SRflipFlop_8_Q : 1'b?;
  assign not_11_out = ~TriState_19_out;
  assign and_4_out = not_9_out & SRflipFlop_9_Q;
  Button2 Button_2(Button_2_out);
  SRflipFlop SRflipFlop_6(SRflipFlop_6_Q, , TriState_7_out, Button_2_out, , , );
  assign TriState_8_out = (SRflipFlop_6_Q!=0) ? inp_0 : 1'b?;
  assign not_5_out = ~TriState_8_out;
  SRflipFlop SRflipFlop_8(SRflipFlop_8_Q, , TriState_8_out, not_5_out, Button_2_out, , );
  assign out_0 = SRflipFlop_8_Q;
  assign xor_3_out = SRflipFlop_7_Q ^ SRflipFlop_6_Q;
  assign not_4_out = ~xor_3_out;
  assign TriState_7_out = (not_4_out!=0) ? TriState_6_out : 1'b?;
  SRflipFlop SRflipFlop_7(SRflipFlop_7_Q, , SRflipFlop_6_Q, Button_1_out, , , );
  assign Button_2_out = not_0_out & SRflipFlop_6_Q;
  Button3 Button_1(Button_1_out);
  SRflipFlop SRflipFlop_3(SRflipFlop_3_Q, , SRflipFlop_0_Q, Button_1_out, , , );
  assign xor_0_out = SRflipFlop_3_Q ^ SRflipFlop_0_Q;
  assign TriState_1_out = (xor_0_out!=0) ? TriState_3_out : 1'b?;
  assign TriState_2_out = (not_2_out!=0) ? TriState_1_out : 1'b?;
  SRflipFlop SRflipFlop_2(SRflipFlop_2_Q, , TriState_2_out, and_1_out, , , );
  assign TriState_8_out = (SRflipFlop_2_Q!=0) ? inp_2 : 1'b?;
  assign xor_1_out = SRflipFlop_4_Q ^ SRflipFlop_2_Q;
  assign TriState_4_out = (xor_1_out!=0) ? TriState_3_out : 1'b?;
  assign TriState_5_out = (not_3_out!=0) ? TriState_4_out : 1'b?;
  SRflipFlop SRflipFlop_1(SRflipFlop_1_Q, , TriState_5_out, and_2_out, , , );
  assign TriState_8_out = (SRflipFlop_1_Q!=0) ? inp_1 : 1'b?;
  assign and_2_out = not_0_out & SRflipFlop_1_Q;
  assign xor_2_out = SRflipFlop_5_Q ^ SRflipFlop_1_Q;
  assign TriState_6_out = (xor_2_out!=0) ? TriState_3_out : 1'b?;
  assign not_3_out = ~xor_2_out;
  SRflipFlop SRflipFlop_5(SRflipFlop_5_Q, , SRflipFlop_1_Q, Button_1_out, , , );
  assign not_2_out = ~xor_1_out;
  SRflipFlop SRflipFlop_4(SRflipFlop_4_Q, , SRflipFlop_2_Q, Button_1_out, , , );
  assign and_1_out = not_0_out & SRflipFlop_2_Q;
  assign not_1_out = ~xor_0_out;
  assign TriState_0_out = (not_1_out!=0) ? TriState_3_out : 1'b?;
  SRflipFlop SRflipFlop_0(SRflipFlop_0_Q, , TriState_0_out, and_0_out, , , );
  assign TriState_8_out = (SRflipFlop_0_Q!=0) ? inp_3 : 1'b?;
  assign and_0_out = not_0_out & SRflipFlop_0_Q;
  Button4 Button_0(Button_0_out);
  assign TriState_3_out = (Button_0_out!=0) ? clk_0 : 1'b?;
  assign not_0_out = ~TriState_3_out;
  assign not_9_out = ~TriState_3_out;
endmodule
// Skeleton for Button0
    /*
    module Button0(out);
      output reg out;
    
      initial begin
        //do something with the button here
      end
    endmodule
    */
    // Skeleton for Button1
    /*
    module Button1(out);
      output reg out;
    
      initial begin
        //do something with the button here
      end
    endmodule
    */
    // Skeleton for Button2
    /*
    module Button2(out);
      output reg out;
    
      initial begin
        //do something with the button here
      end
    endmodule
    */
    // Skeleton for Button3
    /*
    module Button3(out);
      output reg out;
    
      initial begin
        //do something with the button here
      end
    endmodule
    */
    // Skeleton for Button4
    /*
    module Button4(out);
      output reg out;
    
      initial begin
        //do something with the button here
      end
    endmodule
    */
    